return {
  ["<leader>a"] = { group = "AI/AST" },
  ["<leader>ai"] = { group = "AI" },
  ["<leader>aic"] = { group = "ChatGpt" },
  ["<leader>aica"] = { "<cmd>ChatGPTRun add_tests<cr>", desc = "Add Tests" },
  ["<leader>aicd"] = { "<cmd>ChatGPTRun docstring<cr>", desc = "Docstring" },
  ["<leader>aice"] = {
    "<cmd>ChatGPTEditWithInstructions<cr>",
    desc = "Edit with instruction",
  },
  ["<leader>aicf"] = { "<cmd>ChatGPTRun fix_bugs<cr>", desc = "Fix Bugs" },
  ["<leader>aicg"] = {
    "<cmd>ChatGPTRun grammar_correction<cr>",
    desc = "Grammar Correction",
  },
  ["<leader>aick"] = { "<cmd>ChatGPTRun keywords<cr>", desc = "Keywords" },
  ["<leader>aicl"] = {
    "<cmd>ChatGPTRun code_readability_analysis<cr>",
    desc = "Code Readability Analysis",
  },
  ["<leader>aico"] = {
    "<cmd>ChatGPTRun optimize_code<cr>",
    desc = "Optimize Code",
  },
  ["<leader>aicp"] = { "<cmd>ChatGPTActAs<cr>", desc = "Open prompt" },
  ["<leader>aicr"] = {
    "<cmd>ChatGPTRun roxygen_edit<CR>",
    desc = "Roxygen Edit",
  },
  ["<leader>aics"] = { "<cmd>ChatGPTRun summarize<cr>", desc = "Summarize" },
  ["<leader>aict"] = { "<cmd>ChatGPTRun translate<cr>", desc = "Translate" },
  ["<leader>aicw"] = { "<cmd>ChatGPT<cr>", desc = "Open window" },
  ["<leader>aicx"] = {
    "<cmd>ChatGPTRun explain_code<cr>",
    desc = "Explain Code",
  },
  ["<leader>ait"] = { group = "Tabnine" },
  ["<leader>aitc"] = { "<cmd>TabnineChat<cr>", desc = "Chat With Tabnine" },
  ["<leader>aith"] = { "<cmd>TabnineHub<cr>", desc = "Open TabnineHub" },
  ["<leader>aits"] = { "<cmd>TabnineStatus<cr>", desc = "Show Tabnine Status" },
  ["<leader>aitt"] = { "<cmd>TabnineToggle<cr>", desc = "Toggle Tabnine" },
  ["<leader>aig"] = { group = "Gen" },
  ["<leader>aigC"] = { "<cmd>Gen Change<cr>", desc = "Change" },
  ["<leader>aiga"] = { "<cmd>Gen Ask<cr>", desc = "Ask" },
  ["<leader>aigc"] = { "<cmd>Gen Chat<cr>", desc = "Chat" },
  ["<leader>aige"] = { "<cmd>Gen Enhance_Code<cr>", desc = "Enhance code" },
  ["<leader>aigg"] = { "<cmd>Gen Generate<cr>", desc = "Generate" },
  ["<leader>aigl"] = { "<cmd>Gen Make_List<cr>", desc = "Make list" },
  ["<leader>aigm"] = { "<cmd>Gen Make_Concise<cr>", desc = "Make concise" },
  ["<leader>aigo"] = { "<cmd>Gen Change_Code<cr>", desc = "Change code" },
  ["<leader>aigp"] = { "<cmd>Gen<cr>", desc = "Select prompt" },
  ["<leader>aigr"] = { "<cmd>Gen Review_Code<cr>", desc = "Review code" },
  ["<leader>aigs"] = {
    "<cmd>Gen Enhance_Grammar_Spelling<cr>",
    desc = "Enhance grammar spelling",
  },
  ["<leader>aigt"] = { "<cmd>Gen Make_Table<cr>", desc = "Make table" },
  ["<leader>aigu"] = { "<cmd>Gen Summarize<cr>", desc = "Summarize" },
  ["<leader>aigw"] = {
    "<cmd>Gen Enhance_Wording<cr>",
    desc = "Enhance wording",
  },
  ["<leader>as"] = { group = "AST" },
  ["<leader>asc"] = { "<cmd>TSContextToggle<cr>", desc = "Toggle code context" },
  ["<leader>ase"] = { "<cmd>EditQuery<cr>", desc = "Show live query editor" },
  ["<leader>ash"] = {
    "<cmd>Inspect<cr>",
    desc = "Highlight groups under the cursor",
  },
  ["<leader>ass"] = { "<cmd>TSUpdateSync<cr>", desc = "Update language sync" },
  ["<leader>ast"] = { "<cmd>InspectTree<cr>", desc = "Show syntax tree" },
  ["<leader>asu"] = { "<cmd>TSUpdate<cr>", desc = "Update language" },
}
