return {
  ["<leader>n"] = { group = "Note/Nav/Notify" },
  ["<leader>nt"] = { group = "Note" },
  ["<leader>ntm"] = { group = "Markview" },
  ["<leader>ntmv"] = {
    "<cmd>Markview splitToggle<cr>",
    desc = "Toggle vertical split view",
  },
  ["<leader>nto"] = { group = "Obsidian" },
  ["<leader>ntoc"] = {
    "<cmd>ObsidianLinkNew<cr>",
    desc = "Create note and link",
  },
  ["<leader>ntod"] = {
    "<cmd>ObsidianYesterday<cr>",
    desc = "Daily note for yesterday",
  },
  ["<leader>ntof"] = {
    "<cmd>ObsidianFollowLink<cr>",
    desc = "Follow note under cursor",
  },
  ["<leader>ntoi"] = { "<cmd>ObsidianTemplate<cr>", desc = "Insert template" },
  ["<leader>ntol"] = { "<cmd>ObsidianLink<cr>", desc = "Link to a note" },
  ["<leader>nton"] = { "<cmd>ObsidianNew<cr>", desc = "New note" },
  ["<leader>ntoo"] = { "<cmd>ObsidianOpen<cr>", desc = "Open in obsidian" },
  ["<leader>ntoq"] = { "<cmd>ObsidianQuickSwitch<cr>", desc = "Quickly switch" },
  ["<leader>ntor"] = { "<cmd>ObsidianBacklinks<cr>", desc = "References list" },
  ["<leader>ntos"] = { "<cmd>ObsidianSearch<cr>", desc = "Search for notes" },
  ["<leader>ntot"] = { "<cmd>ObsidianToday<cr>", desc = "Daily note" },
  ["<leader>ntow"] = { "<cmd>ObsidianWorkspace<cr>", desc = "Switch workspace" },
  ["<leader>na"] = { group = "Nav" },
  ["<leader>nab"] = { "<cmd>Telescope resume<cr>", desc = "Resume" },
  ["<leader>nac"] = { "<cmd>Telescope commands<cr>", desc = "Commands" },
  ["<leader>nah"] = { "<cmd>Telescope help_tags<cr>", desc = "Find Help" },
  ["<leader>nak"] = { "<cmd>Telescope keymaps<cr>", desc = "Keymaps" },
  ["<leader>nam"] = { "<cmd>Telescope man_pages<cr>", desc = "Man Pages" },
  ["<leader>nar"] = { "<cmd>Telescope registers<cr>", desc = "Registers" },
  ["<leader>nas"] = { "<cmd>Telescope colorscheme<cr>", desc = "Colorscheme" },
  ["<leader>nai"] = { "<cmd>e $MYVIMRC<cr>", desc = "Open init.lua" },
  ["<leader>naS"] = {
    function()
      vim.cmd.edit(CONFIG_PATH .. "/snippets/package.json")
    end,
    desc = "Open snippets",
  },
  ["<leader>nao"] = { "<cmd>Outline<cr>", desc = "Toggle outline" },
  ["<leader>no"] = { group = "Notification" },
  ["<leader>noD"] = { "<cmd>NoiceDisable<cr>", desc = "Noice Disable" },
  ["<leader>noE"] = { "<cmd>NoiceEnable<cr>", desc = "Noice Enable" },
  ["<leader>noa"] = { "<cmd>NoiceDismiss<cr>", desc = "Noice Dismiss all" },
  ["<leader>nod"] = {
    "<cmd>DissmissNotification<cr>",
    desc = "Dismiss notifications",
  },
  ["<leader>noe"] = { "<cmd>NoiceErrors<cr>", desc = "Noice errors" },
  ["<leader>noh"] = { "<cmd>NoiceHistory<cr>", desc = "Noice history" },
  ["<leader>nol"] = { "<cmd>NoiceLast<cr>", desc = "Noice last message" },
  ["<leader>non"] = { "<cmd>Notifications<cr>", desc = "Show notifications" },
  ["<leader>nos"] = { "<cmd>NoiceStats<cr>", desc = "Noice stats" },
  ["<leader>not"] = {
    "<cmd>NoiceTelescope<cr>",
    desc = "Noice telescope history",
  },
}
