# tmux light theme (sourced by tmux-dark-notify)
set -g @tmux_power_theme 'snow'
set -g @tmux_power_right_arrow_icon ' '
set -g @tmux_power_left_arrow_icon  ' '
run -b '$HOME/.config/tmux/plugins/tmux-power/tmux-power.tmux'
setw -g pane-border-style "fg=#c8c8c8"
setw -g pane-active-border-style "fg=#c8c8c8"
