require("features.disable-providers")
require("features.qf-del-bind-and-stop-auto-scroll")
require("features.reset-buffer")
require("features.filter-diagnostic")
require("features.watch-system-info")
require("features.auto-install")
require("features.auto-view")
