format = """
[░▒▓](#a3aed2)\
[](fg:#a3aed2 bg:#769ff0)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$all\
$character"""

command_timeout = 5000

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
home_symbol='~'
format = '[ $path ]($style)[$read_only]($read_only_style)'
truncation_length = 0
truncate_to_repo = false
use_logical_path = true
read_only_style = '197'
read_only = '?'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind)](fg:#769ff0 bg:#394260)]($style)'
conflicted = '[ confliced=${count}](fg:red bg:#394260)'
up_to_date = '[󰘽 up-to-date](fg:green bg:#394260)'
untracked = '[󰋗 untracked=${count}](fg:red bg:#394260)'
ahead = ' ahead=${count}(bg:#394260)'
diverged = ' ahead=${ahead_count} behind=${behind_count}(bg:#394260)'
behind = ' behind=${count}(bg:#394260)'
stashed = '[ stashed=${count}](fg:green bg:#394260)'
modified = '[󰛿 modified=${count}](fg:yellow bg:#394260)'
staged = '[󰐗 staged=${count}](fg:green bg:#394260)'
renamed = '[󱍸 renamed=${count}](fg:yellow bg:#394260)'
deleted = '[󰍶 deleted=${count}](fg:red bg:#394260)'

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'fg:blue bg:#212736'
symbol = "? "

[kubernetes]
symbol = '☸ '
disabled = false
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
]

[docker_context]
disabled = true

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
